# Copyright 2019 The SEED Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM tensorflow/tensorflow:2.1.0-gpu-py3

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  git \
  cmake \
  build-essential \
  libgl1-mesa-dev \
  libsdl2-dev \
  libsdl2-image-dev \
  libsdl2-ttf-dev \
  libsdl2-gfx-dev \
  libboost-all-dev \
  libdirectfb-dev \
  libst-dev \
  glee-dev \
  mesa-utils \
  xvfb \
  x11vnc \
  libsdl-sge-dev \
  python3-pip \
  libboost-all-dev \
  libboost-python-dev \
  tmux

# gym_unity 16.1 here
RUN pip3 install tensorflow_probability==0.9.0 opencv-python gym-unity


# Copy SEED codebase and SEED GRPC binaries.
ADD . /seed_rl/

WORKDIR /seed_rl

EXPOSE 5004-5500

ENV DISPLAY=:100

ENTRYPOINT ["unity/start.sh"]